# Generated by Django 4.2.10 on 2024-03-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actual", models.DecimalField(decimal_places=1, max_digits=5)),
                ("forecast", models.DecimalField(decimal_places=15, max_digits=20)),
                ("upper", models.DecimalField(decimal_places=15, max_digits=20)),
                ("lower", models.DecimalField(decimal_places=15, max_digits=20)),
                ("date_time", models.TextField()),
            ],
        ),
    ]
