# Generated by Django 4.2.10 on 2024-03-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Post", new_name="Bikes",),
    ]
