# Generated by Django 4.2.10 on 2024-03-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0002_rename_post_bikes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikes", name="date_time", field=models.TextField(unique=True),
        ),
    ]
