# Generated by Django 4.2.10 on 2024-03-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0005_alter_bikes_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikes",
            name="forecast",
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="bikes",
            name="lower",
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="bikes",
            name="upper",
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True),
        ),
    ]
