# Generated by Django 4.2.10 on 2024-03-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0006_alter_bikes_forecast_alter_bikes_lower_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="bikes", name="id",),
        migrations.AlterField(
            model_name="bikes",
            name="date_time",
            field=models.DateTimeField(primary_key=True, serialize=False, unique=True),
        ),
    ]
